import React from 'react';
import { Box, Typography } from '@mui/material';
import { useAuthContext } from '../../../context/AuthContext';

const PrintDocumentFooter = ({ shopName, documentName }) => {
  const { user } = useAuthContext();
  const userName = user?.name || user?.username || user?.sub || 'System Admin';

  const timestamp = new Date().toLocaleString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
    hour12: false
  });

  return (
    <Box sx={{ mt: 2, pt: 0.8, borderTop: '1px solid #000000', pageBreakInside: 'avoid', width: '100%' }}>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 0.2 }}>
        <Typography variant="caption" sx={{ color: '#000000', fontSize: '0.66rem', fontWeight: 700 }}>
          Generated by VyaparSathi ERP
        </Typography>
        <Typography variant="caption" sx={{ color: '#000000', fontSize: '0.66rem', fontWeight: 600 }}>
          Generated On: {timestamp}
        </Typography>
        <Typography variant="caption" sx={{ color: '#000000', fontSize: '0.66rem', fontWeight: 600 }}>
          Printed By: {userName}
        </Typography>
        <Typography variant="caption" sx={{ color: '#000000', fontSize: '0.66rem', fontWeight: 700 }}>
          Page 1 of 1
        </Typography>
      </Box>

      <Typography variant="caption" sx={{ color: '#444444', fontSize: '0.62rem', display: 'block', textAlign: 'center', fontStyle: 'italic', mt: 0.3 }}>
        This is a computer-generated document and does not require a physical signature.
      </Typography>
    </Box>
  );
};

export default PrintDocumentFooter;
